variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "gradle-$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/caches

stages:
  - "build"
  - "test"

test build:
  stage: "build"
  # TODO: use minepkg gradle image
  image: gradle:5.6.2-jdk8
  script:
    - gradle build -x test
  artifacts:
    paths:
      - build/libs

unit test:
  stage: "test"
  needs: []
  image: gradle:5.6.2-jdk8
  script:
    - gradle test

crash-test 1.14:
  stage: "test"
  image: openjdk:8-jdk
  script:
    - curl -L "https://storage.googleapis.com/minepkg-client/latest/minepkg-linux-amd64" -o /usr/local/bin/minepkg
    - chmod +x /usr/local/bin/minepkg
    - cd ./test-manifests/1.14
    - mkdir -p mods
    - cp -f ../../build/libs/MinepkgCompanion-*.*.[0-9].jar mods/minepkg-companion-custom.jar
    - minepkg launch --server --crashtest --accept-eula --offline --system-java
  cache:
    key: "server-1.14-$CI_COMMIT_REF_SLUG"
    paths:
      - test-manifests/1.14

crash-test 1.15:
  stage: "test"
  image: openjdk:8-jdk
  script:
    - curl -L "https://storage.googleapis.com/minepkg-client/latest/minepkg-linux-amd64" -o /usr/local/bin/minepkg
    - chmod +x /usr/local/bin/minepkg
    - cd ./test-manifests/1.15
    - mkdir -p mods
    - cp -f ../../build/libs/MinepkgCompanion-*.*.[0-9].jar mods/minepkg-companion-custom.jar
    - minepkg launch --server --crashtest --accept-eula --offline --system-java
  cache:
    key: "server-1.15-$CI_COMMIT_REF_SLUG"
    paths:
      - test-manifests/1.15
